name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: Provide Firebase Android
        env:
          FIREBASE_CONFIG_DEV: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $FIREBASE_CONFIG_DEV > ./app/google-services.json

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble